name: Linux Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check repository
        run: |
          echo "Current directory:"
          pwd

          echo "Repository contents:"
          ls -la

          echo "README contents:"
          cat README.md

      - name: Check Git
        run: |
          git status
          git log --oneline -5
